apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: gcr.io/gcp-docker-cicd/django-helloworld:latest  # Will be updated with GitHub SHA
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: gcr-json-key  # Use GCR authentication secret
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
